# Generated by Django 3.2.13 on 2022-06-27 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_active_myuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpluser',
            name='referral_code',
            field=models.CharField(default='2c34Ed', max_length=6, verbose_name='Referral Code'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Referral Code')),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred', to='accounts.fpluser')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to='accounts.fpluser')),
            ],
            options={
                'unique_together': {('referrer', 'referred')},
            },
        ),
    ]
