# Generated by Django 3.2.13 on 2022-06-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220628_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpluser',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
