# Generated by Django 3.2.13 on 2022-06-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fpluser_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpluser',
            name='refer_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fpluser',
            name='total_referrals',
            field=models.IntegerField(default=0),
        ),
    ]
