# Generated by Django 3.2.13 on 2022-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl_data', '0002_auto_20220623_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='t_id',
            field=models.IntegerField(unique=True, verbose_name='Transaction ID'),
        ),
    ]
