# Generated by Django 3.2.14 on 2022-07-04 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fpl_data', '0003_alter_prediction_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
