# Generated by Django 3.2.13 on 2022-06-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl_data', '0003_alter_token_t_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
