# Generated by Django 3.2.13 on 2022-06-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpl_data', '0004_auto_20220623_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='prediction',
        ),
        migrations.AddField(
            model_name='prediction',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fpl_data.token'),
        ),
    ]
